services:
  db:
    container_name: csdl-db
    image: mariadb:10.5.9
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - csdl-db-volume:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: csdl-app
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - ./src/app:/usr/src/app
    command: "/usr/src/entrypoint.dev.sh"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  csdl-db-volume:
