"""Fixing typo

Revision ID: 79447245343b
Revises: bf2dad266504
Create Date: 2021-03-26 03:28:56.500907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79447245343b'
down_revision = 'bf2dad266504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candlestick', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('candlestick', 'upated_at')
    op.add_column('currency', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('currency', 'upated_at')
    op.add_column('currency_pair', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('currency_pair', 'upated_at')
    op.add_column('exchange', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('exchange', 'upated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('upated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('exchange', 'updated_at')
    op.add_column('currency_pair', sa.Column('upated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('currency_pair', 'updated_at')
    op.add_column('currency', sa.Column('upated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('currency', 'updated_at')
    op.add_column('candlestick', sa.Column('upated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('candlestick', 'updated_at')
    # ### end Alembic commands ###
