"""Adding market to CurencyPair

Revision ID: bf2dad266504
Revises: 3a8066d4f680
Create Date: 2021-03-19 00:37:19.515199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf2dad266504"
down_revision = "3a8066d4f680"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currency_pair", sa.Column("market", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("currency_pair", "market")
    # ### end Alembic commands ###
