"""Simplify and add unique constaints

Revision ID: da4e6ed8d2f1
Revises: 79447245343b
Create Date: 2021-03-28 16:54:24.148833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "da4e6ed8d2f1"
down_revision = "79447245343b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "candlestick", ["currency_pair_id", "timestamp"])
    op.alter_column(
        "currency", "name", existing_type=mysql.VARCHAR(length=20), nullable=True
    )
    op.drop_column("currency", "precision")
    op.add_column(
        "currency_pair", sa.Column("currency_base_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "currency_pair", sa.Column("currency_quote_id", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(None, "currency_pair", ["exchange_id", "symbol"])
    op.drop_constraint("currency_pair_ibfk_1", "currency_pair", type_="foreignkey")
    op.drop_constraint("currency_pair_ibfk_2", "currency_pair", type_="foreignkey")
    op.create_foreign_key(
        None, "currency_pair", "currency", ["currency_base_id"], ["id"]
    )
    op.create_foreign_key(
        None, "currency_pair", "currency", ["currency_quote_id"], ["id"]
    )
    op.drop_column("currency_pair", "currency_b_id")
    op.drop_column("currency_pair", "currency_a_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "currency_pair",
        sa.Column(
            "currency_a_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "currency_pair",
        sa.Column(
            "currency_b_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "currency_pair", type_="foreignkey")
    op.drop_constraint(None, "currency_pair", type_="foreignkey")
    op.create_foreign_key(
        "currency_pair_ibfk_2", "currency_pair", "currency", ["currency_b_id"], ["id"]
    )
    op.create_foreign_key(
        "currency_pair_ibfk_1", "currency_pair", "currency", ["currency_a_id"], ["id"]
    )
    op.drop_constraint(None, "currency_pair", type_="unique")
    op.drop_column("currency_pair", "currency_quote_id")
    op.drop_column("currency_pair", "currency_base_id")
    op.add_column(
        "currency",
        sa.Column(
            "precision",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "currency", "name", existing_type=mysql.VARCHAR(length=20), nullable=False
    )
    op.drop_constraint(None, "candlestick", type_="unique")
    # ### end Alembic commands ###
